POST http://localhost:3333/events
Content-Type: application/json


{
    "title": "Novo evento 2",
    "details": "Evento de programação",
    "maximumAttendees": 1
}

###


POST http://localhost:3333/events/e65f69a3-cf0a-4f02-9245-7e15325d2697/attendees
Content-Type: application/json


{
    "name": "Lucas Batista",
    "email": "lucas_03@gmail.com"
}

###
GET http://localhost:3333/events/e65f69a3-cf0a-4f02-9245-7e15325d2697

###
GET http://localhost:3333/attendees/4/badge

###
GET http://localhost:3333/attendees/4/check-in

###
GET http://localhost:3333/events/e65f69a3-cf0a-4f02-9245-7e15325d2697/attendees